### ISSUE TITLE
Doesn't work in IE 11 nor in IE Edge

### ISSUE THREAD

**Issue by asadmalik3** [kbatyrbayev/ng-pdf-highlighter#1]
Hi,

Your plugin doesn't work in internet explorer nor in edge. Are you going to fix it?

**Comment by kbatyrbayev** [comment]
Hello, currently only works in chrome.
I will definitely fix it in other browsers.

**Comment by asadmalik3** [comment]
@kbatyrbayev is there a timeline or a road map?

**Comment by kbatyrbayev** [comment]
> @kbatyrbayev is there a timeline or a road map?

Sorry for the late reply, fixed the error in IE 11. Please check in Edge, I have no opportunity to check on it.
Thank you.
