### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by dharam116** [kbatyrbayev/ng-pdf-highlighter#2]
Hi, 
I am not able to create a rectangle box on pdf.  I have simple download the code and run npm install and then ng serve --open but this code is not working.
Please help I needed this code.

thanks

**Comment by kbatyrbayev** [comment]
Hi, what error comes out?

**Comment by kbatyrbayev** [comment]
And, so far, my code only works in Google Chrome and Firefox

**Comment by dharam116** [comment]
Hi, the rectangle is not working, CustomeEvent is not working.

event.path.find(p => p.className == 'page').appendChild(elem);

event.path is showing undefined.


thanks

**Comment by kbatyrbayev** [comment]
> Hi, the rectangle is not working, CustomeEvent is not working.
> 
> event.path.find(p => p.className == 'page').appendChild(elem);
> 
> event.path is showing undefined.
> 
> thanks

in which browser do you see?

**Comment by dharam116** [comment]
google chrome

**Comment by kbatyrbayev** [comment]
> google chrome

check this [link](https://kbatyrbayev.github.io/ng-pdf-highlighter/),  does it work there?

**Comment by dharam116** [comment]
yes, it is working. Actually some days ago I have tried so this GitHub code is working. but Now It is not working. can you please take a new pull and then do npm install and run this code.

**Comment by kbatyrbayev** [comment]
> yes, it is working. Actually some days ago I have tried so this GitHub code is working. but Now It is not working. can you please take a new pull and then do npm install and run this code.

I take new pull and started it, there are no errors.
My google chrome version: 74.0.3729.169
Local angular cli: 7.3.5
local Node: 8.12.0

______________________

what can I offer you?
if you wait, I will rewrite the code to work in all browsers. It will take about 2-3 days.

**Comment by dharam116** [comment]
> > yes, it is working. Actually some days ago I have tried so this GitHub code is working. but Now It is not working. can you please take a new pull and then do npm install and run this code.
> 
> I take new pull and started it, there are no errors.
> My google chrome version: 74.0.3729.169
> Local angular cli: 7.3.5
> local Node: 8.12.0
> 
> what can I offer you?
> if you wait, I will rewrite the code to work in all browsers. It will take about 2-3 days.

No Problem, I can change into all browser support. 
but I am trying to write code in a new project then also I have a facing problem.
One I will try today again then I will reach you.

Thanks for the support.

**Comment by kbatyrbayev** [comment]
> Hi, the rectangle is not working, CustomeEvent is not working.
> 
> event.path.find(p => p.className == 'page').appendChild(elem);
> 
> event.path is showing undefined.
> 
> thanks

I fixed this error in FireFox and Chrome...
